import type { EnemyDef } from '../../core/types';

// ===== 敌方单位数据 =====
export const ENEMIES: Record<string, EnemyDef> = {
  goblin: {
    id: 'goblin',
    name: '哥布林',
    element: 'none',
    aiRole: 'melee',
    level: 1,
    stats: { hp: 26, mp: 0, atk: 8, def: 4, mag: 3, res: 2, spd: 6, mov: 4, luk: 3 },
    skills: [],
    expReward: 22,
    goldReward: 12,
    spriteKey: 'spr-goblin',
    portraitKey: 'por-goblin',
    color: 0x8fbf6a,
  },
  skeleton: {
    id: 'skeleton',
    name: '骷髅剑士',
    element: 'dark',
    aiRole: 'melee',
    level: 2,
    stats: { hp: 34, mp: 0, atk: 10, def: 7, mag: 4, res: 4, spd: 5, mov: 4, luk: 4 },
    skills: [],
    expReward: 30,
    goldReward: 18,
    spriteKey: 'spr-skeleton',
    portraitKey: 'por-skeleton',
    color: 0xcfd8dc,
  },
  orc: {
    id: 'orc',
    name: '兽人狂战士',
    element: 'none',
    aiRole: 'melee',
    level: 3,
    stats: { hp: 50, mp: 0, atk: 14, def: 6, mag: 3, res: 3, spd: 5, mov: 4, luk: 5 },
    skills: [],
    expReward: 40,
    goldReward: 28,
    spriteKey: 'spr-orc',
    portraitKey: 'por-orc',
    color: 0xd9884a,
  },
  cultist: {
    id: 'cultist',
    name: '黑暗教徒',
    element: 'dark',
    aiRole: 'ranged',
    level: 3,
    stats: { hp: 30, mp: 30, atk: 4, def: 4, mag: 12, res: 10, spd: 6, mov: 4, luk: 6 },
    skills: ['enemy_dark_bolt'],
    expReward: 42,
    goldReward: 30,
    spriteKey: 'spr-cultist',
    portraitKey: 'por-cultist',
    color: 0xb07ae0,
  },
  gargoyle: {
    id: 'gargoyle',
    name: '石像鬼',
    element: 'none',
    aiRole: 'melee',
    level: 4,
    stats: { hp: 58, mp: 0, atk: 12, def: 12, mag: 4, res: 8, spd: 4, mov: 3, luk: 4 },
    skills: [],
    expReward: 55,
    goldReward: 40,
    spriteKey: 'spr-gargoyle',
    portraitKey: 'por-gargoyle',
    color: 0x90a4ae,
  },
  dark_priest: {
    id: 'dark_priest',
    name: '暗黑主教',
    element: 'dark',
    aiRole: 'healer',
    level: 4,
    stats: { hp: 36, mp: 40, atk: 4, def: 5, mag: 13, res: 12, spd: 6, mov: 4, luk: 7 },
    skills: ['enemy_drain'],
    expReward: 58,
    goldReward: 45,
    spriteKey: 'spr-dark-priest',
    portraitKey: 'por-dark-priest',
    color: 0x8e6bb8,
  },
  chaos_knight: {
    id: 'chaos_knight',
    name: '堕落骑士·卡奥斯',
    element: 'dark',
    aiRole: 'boss',
    level: 8,
    stats: { hp: 130, mp: 40, atk: 18, def: 12, mag: 14, res: 10, spd: 8, mov: 5, luk: 8 },
    skills: ['boss_dread_slash', 'boss_dark_wave'],
    expReward: 220,
    goldReward: 300,
    spriteKey: 'spr-chaos-knight',
    portraitKey: 'por-chaos-knight',
    color: 0x9c27b0,
    boss: true,
  },
};

export function getEnemy(id: string): EnemyDef {
  return ENEMIES[id];
}
